### PR TITLE
Adding new sample to explain the concepts behind ETags

### PR DESCRIPTION
**Pull request by bitsforthought**
This sample code will be used in a new article on concurrency and ETags in Azure Search.

### CODE REVIEW

**Comment by bitsforthought** [comment]
@mhko @HeidiSteen I can't seem to add you as reviewers. Please take a look at this PR. It's sample code for the ETags article.

**Comment by HeidiSteen** [comment]
Looks great!!  I love the narrative comments.  In the docs, Etags is an implementation detail and we used "access condition" as the 'concept', but Etags works better in the comments.  I'll rebalance terms in the docs to match the code.

Code: I didn't fork your branch and run the sample myself, but I will run it once its live.

**Comment by mhko** [comment]
LGTM. 

For synonyms sample, I suppose we just want to expose the etag string in the console after each update?

**Comment by bitsforthought** [comment]
@mhko No, the synonyms sample should implement concurrency-safe update in a way that customers can use as a template.

**Pull request merged**
