### PR TITLE
Update all the dependencies to the latest. Search SDK to 10.1 for DotnetSample

### PR DESCRIPTION
**Pull request by nithinmohantk**
… to support newer frameworks.

*verified both JS and C# samples and working as expected. 

#39 addressed

### CODE REVIEW

**Comment by bitsforthought** [comment]
FYI @mrcarter8

**Comment by bitsforthought** [comment]
@nithinmohantk Some comments were left by @mrcarter8 on the issue to which you linked. I think they should have been here:

> Thanks for taking the time to make these updates. The changes related to the referenced SDK version are great. No concerns there. I'm not sure about the changes to the JS and CSS files in the autocomplete sample, thought. Could you explain more about why these were needed and what they do?

**Comment by nithinmohantk** [comment]
@brjohnstmsft  @mrcarter8 Either way this updates the samples to latest framework components, some of them are outdated as I mentioned. 
Like it was mentioned in #39, we had to make some changes to make it working once we update the Nuget components to support in new projects. I am submitting the changes back to repo, as it keeps the repo up to date. 

PS: #39 was only addressing one project issue. But I made the following projects up to date. 

Kindly review and incorporate the same, than leaving it with outdated components. 
**Change Log:** 
- Upgraded Search SDK 10.1 for DotNetHowTo Project (DotnetCore)
- Upgraded to Azure Search SDK 10.1 for DotNetHowToIndexers
- Upgraded Search SDK to 10.1 for DotNetHowToMultipleDataSources
- Upgraded Search SDK to 10.1 from v5.0 for [DotNetETagsExplainer]
- .NET Core components are updated to 3.1.1 , as 2.x.x is End of Life
- JQuery libraries are updated to the latest to keep up to date.

**Comment by nithinmohantk** [comment]
@brjohnstmsft @mrcarter8 I am going to close the pull request if there is no action taken. Every time, when I create a pull request, Microsoft teams take up to two weeks or more to review, which is ridiculous in the open-source world. Why do you open source these codes, if you are not open for contributions?

**Comment by bitsforthought** [comment]
@nithinmohantk I apologize for the delay in reviewing this PR. The reality is that we don't have many engineers available right now to review PRs for sample code due to other priorities. We are debating right now whether to move the samples for Azure Cognitive Search to more of a shared-source model and stop accepting PRs, since we don't want to continue causing frustration for contributors like you.

I want to emphasize that this is a specific issue with the Azure Cognitive Search samples. If you contribute to Azure SDKs or to content on docs.microsoft.com via GitHub, you can expect much better response times for PRs.

**Comment by nithinmohantk** [comment]
@mrcarter8  @brjohnstmsft  Gentle reminder...

**Comment by mrcarter8** [comment]
@nithinmohantk Can you provide a high level overview of the changes you made to the Autocomplete sample?  I'd like to understand what JS changes you thought were required.  I did a pass in January and it all ran fine in every latest browser I tried with no errors or missing functionality.

To the other changes about making sure we point the sample projects at the latest version of our SDK, I completely agree and that's our fault.  We'll make sure to keep these more up to date in the future.

**Comment by nithinmohantk** [comment]
@mrcarter8  As part of upgrade, I just updated jQuery reference to latest version, that's all.  There was no functional issue. 
Now after one month of creating this pull request, can you approve it.  Hope you understand I only made changes that are essential.

**Review by mrcarter8 — CHANGES_REQUESTED** [review]
Please remove any unneccesary js files.  The popper and response JS libraries appear to be unused.  If you can minimize the change to ONLY updating jquery to the latest, we will approve the change.  Thanks.

**Comment by nithinmohantk** [comment]
@mrcarter8  If you analyze carefully, Popper.js, Response.js are dependency for Bootstrap 4.4.1, since you are particular. I will downgrade them for the sake of community and developers who would appreciate the updated code to be merged.

**Review by mrcarter8 — APPROVED** [review]

**Pull request merged**
