### PR TITLE
Upgraded nuget packages and made it work with latest Azure Search SDK..

### PR DESCRIPTION
**Pull request by nithinmohantk**
* Updated Azure Search SDK components 
* Upgraded JS libraries

### CODE REVIEW

**Comment by bitsforthought** [comment]
@nithinmohantk Sorry this went unnoticed. I'll try to find the right owner to review and merge this.

@mrcarter8 Were you the original author of this sample? If not, do you know who was? Trying to find the right person to review this.

@HeidiSteen Is this still the right repo for this sample?

**Comment by nithinmohantk** [comment]
It is really unwelcoming to see, a pull request not been reviewed after 20 days. Why to open source then?

**Comment by bitsforthought** [comment]
@nithinmohantk Apologies for the delay. The owners of this sample have been traveling for several weeks. @liamca is now reviewing and testing your changes.

**Comment by nithinmohantk** [comment]
27 days and still waiting :-). Probably a new version of dependent libraries released in B/w..

**Comment by liamca** [comment]
As Bruce mentioned, I apologize for the delay.  When I tried to test this I was not able to get it to run.  Run of the initial issues I hit was a reference to jQuery that was not in the project.  I am curious, did you have that issue?  Would you mind trying to see if this runs for you?

**Comment by nithinmohantk** [comment]
I was able to run it successfully and that's the reason I pushed it back to repository assuming it would be useful for all. Appears now it is conflicted. I am cancelling my pull request, it ain't worth it.

**Pull request closed without merging**
